create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  reference text unique not null,
  customer_name text not null,
  customer_phone text not null,
  delivery_location text not null,
  landmark text default '',
  total_amount numeric(12,2) not null,
  currency text not null default 'GHS',
  status text not null default 'Paid',
  items jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);

-- The service-role key is used only by the Vercel API.
-- Do not put the service-role key in the website or GitHub.
